const escapeHtml = (value = '') => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');
const safeLink = ({ label, href } = {}) => href?.startsWith('http') ? `<a href="${escapeHtml(href)}" target="_blank" rel="noreferrer">${escapeHtml(label)}</a>` : escapeHtml(label);
function setDate(data) { document.querySelectorAll('#updated-date').forEach((el) => { el.textContent = data.updated ?? 'див. джерельний план'; }); }
function renderPlan(data) { const root = document.querySelector('#plan-content'); if (!root) return; root.innerHTML = data.plan.map((item, index) => `<article class="phase"><div class="phase-heading"><span>${String(index + 1).padStart(2, '0')}</span><div><h2>${escapeHtml(item.area)}</h2><p>${escapeHtml(item.status)}</p></div></div><ol class="next-steps"><li>${escapeHtml(item.nextStep)}</li></ol><p class="source-note">Пов'язаний документ: ${safeLink(item.document)}</p></article>`).join(''); }
function renderKnowledge(data) {
  const timeline = document.querySelector('#timeline-content'); if (timeline) timeline.innerHTML = data.timeline.map((item) => `<div class="timeline-item"><span>${escapeHtml(item.when)}</span><p><strong>${escapeHtml(item.event)}</strong><br />${escapeHtml(item.action)}<br />${safeLink(item.source)}</p></div>`).join('');
  const decisions = document.querySelector('#decisions-content'); if (decisions) decisions.innerHTML = `<ul class="plain-list">${data.decisions.map((item) => `<li>${escapeHtml(item)}</li>`).join('')}</ul>`;
  const archive = document.querySelector('#archive-content'); if (archive) archive.innerHTML = `<p>Локальний Telegram-індекс допомагає знаходити теми та практичні питання. Він не публікується; повідомлення, автори, контакти, запрошення й вкладення залишаються поза GitHub.</p><ul class="plain-list">${data.archive.summary.map((item) => `<li>${escapeHtml(item)}</li>`).join('')}</ul><p class="source-note">Перевірка цілісності: ${data.archive.integrity.map(escapeHtml).join(' · ')}</p>`;
  const sources = document.querySelector('#sources-content'); if (sources) sources.innerHTML = `<ul class="source-list">${data.sources.map((item) => `<li><div>${safeLink(item.source)}<small>Перевірено: ${escapeHtml(item.checked)}</small></div><span><strong>${escapeHtml(item.topic)}</strong><br />${escapeHtml(item.summary)}</span></li>`).join('')}</ul>`;
  const journal = document.querySelector('#journal-content'); if (journal) journal.innerHTML = data.journal.map((entry) => `<article class="journal-entry"><h3>${escapeHtml(entry.title)}</h3><ul class="plain-list">${entry.points.map((point) => `<li>${escapeHtml(point)}</li>`).join('')}</ul></article>`).join('');
}
async function start() { try { const response = await fetch('site-data.json', { cache: 'no-store' }); if (!response.ok) throw new Error('site-data.json is unavailable'); const data = await response.json(); setDate(data); renderPlan(data); renderKnowledge(data); } catch { document.querySelectorAll('.loading').forEach((el) => { el.textContent = 'Не вдалося завантажити згенеровані публічні дані. Спробуйте оновити сторінку.'; }); } }
start();
